version: "2.1"

networks:
  tools:
    external:
      name: tools

volumes:
  jenkins_home:
    name: jenkins_home
  nexus-data:
    name: nexus-data


services:
  jenkins:
    build: jenkins
    container_name: jenkins_demo
    ports:
      - 8081:8080
    volumes:
      - jenkins_home:/var/jenkins_home
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    group_add:
      - 133
    networks:
      - tools
  tomcat:
    build: tomcat
    container_name: tomcat_demo
    ports:
      - 8082:8080
    networks:
      - tools
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus_demo
    ports:
      - 8083:8081
    networks:
      - tools
    volumes:
      - nexus-data:/nexus-data
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube_demo
    ports:
      - 8084:9000
    networks:
      - tools
  mysql:
    image: mysql:latest
    container_name: mysql_demo
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_USER=root
    ports:
    - 8085:3306
    networks:
      - tools

